[package]
name = "webcloner-gui"
version = "1.0.0"
description = "Graphical interface for webcloner"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
webcloner = { path = "../.." }
tauri = { version = "1", features = ["shell-open", "dialog-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "=2.5.0"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[[bin]]
name = "webcloner-gui"
path = "src/main.rs"
